config/routes.rb
Rails.application.routes.draw do
  root :to => 'lists#index'

  resources :lists do
    resources :tasks, :except => [:show, :index]
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  scope :done, -> { where(done: true) }
  scope :not_done, -> { where(done: false) }
  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List successfully saved!"
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      flash[:notice] = "List successfully updated!"
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash[:alert] = "List successfully deleted!"
    end
    redirect_to lists_path
  end

private
  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      flash[:notice] = "Task successfully saved!"
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "Task successfully updated!"
      redirect_to list_path(@task.list)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:alert] = "Task successfully deleted!"
    end
    redirect_to lists_path
  end

private
  def task_params
    params.require(:task).permit(:description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus=>true %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<% content_for(:title, "Edit | Todo") %>

<h1>Edit List</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<% content_for(:title, "Rails | Todo") %>

<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Create New List", new_list_path %>

app/views/lists/new.html.erb
<% content_for(:title, "New | Todo") %>

<h1>New List</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>

<h4><%= @list.description %></h4>

<% if @list.tasks.any? %>
  <h4>Here are the tasks for this list:</h4>
  <ul>
  <% @list.tasks.each do |task| %>
    <li>
      <%= task.description %> |
      <%= link_to "Edit", edit_list_task_path(@list, task) %> |
      <%= link_to "Delete", list_task_path(@list, task),
      :data => {:confirm => "You sure?",
        :method => "delete"} %>
    </li>
  <% end %>
  </ul>
<% else %>
  <p>There are no tasks yet!</p>
<% end %>

<hr>

<% if @list.tasks.done %>
  <div class="col-xs-6">
    <h4>Here are the tasks that you have completed:</h4>
    <ul>
      <% @list.tasks.done.each do |task| %>
      <li>
        <%= task.description %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @list.tasks.not_done %>
  <div class="col-xs-6">
    <h4>Here are the tasks that have yet to be completed:</h4>
    <ul>
      <% @list.tasks.not_done.each do |task| %>
      <li>
        <%= task.description %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-xs-12">
  <hr>
  <p><%= link_to "Add a Task", new_list_task_path(@list) %></p>
  <p><%= link_to "Edit", edit_list_path %></p>
  <p><%= link_to "Delete", list_path(@list),
  :data => {:confirm => "You sure?",
            :method => "delete"} %></p>
  <p><%= link_to "Return to Lists", lists_path %></p>
</div>

app/views/tasks/_form.html.erb
<%= render('layouts/errors', :object => @task) %>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.check_box :done %>
  <%= f.label :done, "Task Complete" %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<% content_for(:title, "Edit | Task") %>

<h1>Edit Task</h1>

<%= render 'form' %>

app/views/tasks/new.html.erb
<% content_for(:title, "New Task for" + @list.name) %>

<h1>New task for <%= @list.name %></h1>

<%= render 'form' %>